modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL=""

[[mods]]
modId="cheesemod"
version="1.0.3"
displayName="CheeseMod"
#updateJSONURL=""
displayURL="https://forum.civa.jp/viewtopic.php?f=3&t=304"
logoFile="cheesemod_logo.png"
credits=""
authors="ChumoriPoseidon"
description='''
Add variety cheese items and blocks.
'''

[[dependencies.cheesemod]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.cheesemod]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
